package pages;

import base.BasePage;
import lombok.extern.slf4j.Slf4j;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import userDecorator.DefaultUser;
import userDecorator.UserWithAutoPasswordDecorator;
import userDecorator.UserWithEncodedPasswordDecorator;

@Slf4j
public class LoginPortalPage extends BasePage {
  @FindBy(css = "#text")
  private WebElement usernamePlaceholder;

  @FindBy(css = "#password")
  private WebElement passwordPlaceholder;

  @FindBy(css = "#login-button")
  private WebElement loginButton;

  public LoginPortalPage(WebDriver driver) {
    super(driver);
  }

  public void loginWithDefaultUser(String username, String password) {
    log.debug("Logging in with username: {}", username);
    DefaultUser defaultUser = new DefaultUser(username, password);
    usernamePlaceholder.sendKeys(defaultUser.getUsername());
    passwordPlaceholder.sendKeys(defaultUser.getPassword());
    javascriptExecutor.executeScript("arguments[0].click();", loginButton);
  }

  public void loginWithAutoGeneratedPassword(String username) {
    log.debug("Logging in with username: {}", username);
    DefaultUser defaultUser = new UserWithAutoPasswordDecorator(username);
    usernamePlaceholder.sendKeys(defaultUser.getUsername());
    passwordPlaceholder.sendKeys(defaultUser.getPassword());
    javascriptExecutor.executeScript("arguments[0].click();", loginButton);
  }

  public void loginInWithEncodedPassword(String username, String password) {
    log.debug("Logging in with username: {}", username);
    DefaultUser defaultUser = new UserWithEncodedPasswordDecorator(username, password);
    usernamePlaceholder.sendKeys(defaultUser.getUsername());
    passwordPlaceholder.sendKeys(defaultUser.getPassword());
    javascriptExecutor.executeScript("arguments[0].click();", loginButton);
  }
}
