package testCases.loginPortal;

import org.openqa.selenium.Alert;
import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import pages.LoginPortalPage;
import base.BaseTest;

import java.util.List;

public class LoginPortalTests extends BaseTest {
  private static LoginPortalPage loginPortalPage;
  private static String username;
  private static String password;

  @BeforeMethod
  public void setLoginPortalPage() {
    loginPortalPage = pageFactoryManager.getLoginPortalPage();
    username = propertiesHelper.getProperty("username");
    password = propertiesHelper.getProperty("password");

  }

  @Test
  public void checkLoginWithDefaultUser() {
    homePage.openHomePage();
    homePage.clickOnLoginPortalLink();

    List<String> tabsList = homePage.tabsList();
    homePage.switchToTab(tabsList.get(FIRST));

    loginPortalPage.implicitWait(TIMEOUT);
    loginPortalPage.loginWithDefaultUser(username, password);

    Alert alert = loginPortalPage.switchToAlert();
    String getAlertMessage = loginPortalPage.getAlertText(alert);

    loginPortalPage.acceptAlert(alert);

    Assert.assertEquals(getAlertMessage, "validation failed");
  }

  @Test
  public void checkLoginWithAutoGeneratedPassword() {
    homePage.openHomePage();
    homePage.clickOnLoginPortalLink();

    List<String> tabsList = homePage.tabsList();
    homePage.switchToTab(tabsList.get(FIRST));

    loginPortalPage.implicitWait(TIMEOUT);
    loginPortalPage.loginWithAutoGeneratedPassword(username);

    Alert alert = loginPortalPage.switchToAlert();
    String getAlertMessage = loginPortalPage.getAlertText(alert);

    loginPortalPage.acceptAlert(alert);

    Assert.assertEquals(getAlertMessage, "validation failed");
  }

  @Test
  public void checkLoginWithEncodedPassword() {
    homePage.openHomePage();
    homePage.clickOnLoginPortalLink();

    List<String> tabsList = homePage.tabsList();
    homePage.switchToTab(tabsList.get(FIRST));

    loginPortalPage.implicitWait(TIMEOUT);
    loginPortalPage.loginInWithEncodedPassword(username, password);

    Alert alert = loginPortalPage.switchToAlert();
    String getAlertMessage = loginPortalPage.getAlertText(alert);

    loginPortalPage.acceptAlert(alert);

    Assert.assertEquals(getAlertMessage, "validation failed");
  }
}
